<?php

namespace PMT\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\UnitOfWork;
use PMT\TaskBundle\Entity\Task;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{   
    
    public function getAssignedUsersChoices($object)
    {
        if($object instanceof Project) {
            $qb = $this->createQueryBuilder('u');
            $qb->addOrderBy('u.first_name');
            $qb->addOrderBy('u.last_name');
            $result = $qb->getQuery()->getResult();
        }
        elseif($object instanceof Task) {
            $result = $object->getProject()->getAssignedUsers()->toArray();
        }

        // Add already assigned users (including deleted)
        $this->getEntityManager()->getFilters()->disable('softdeleteable');
        $assigned = $object->getAssignedUsers()->toArray();
        $this->getEntityManager()->getFilters()->enable('softdeleteable');
        
        // duplicates will be squashed by form field
        $result = array_merge($result, $assigned);
        
        return $result;
    }
}