imports:
    - { resource: config_dev.yml }
    - { resource: security_test.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false
    session:
        save_path: %kernel.cache_dir%/sessions

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
        
liip_functional_test: ~

parameters:
    test.client.class: PMT\TestBundle\Test\Client
    
doctrine:
    dbal:
        dbname:   %test_database_name%
        user:     %test_database_user%
        password: %test_database_password%