<?php

namespace PMT\TaskBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskTextRepository extends EntityRepository
{
    
    public function saveText(Task $task)
    {
        if(!($text = $this->find($task->getId())))
        {
            $text = new TaskText();
            $text->setTaskId($task->getId());
        }

        $text->setName($task->getName());
        $text->setDescription($task->getDescription());
        
        $this->getEntityManager()->persist($text);
        $this->getEntityManager()->flush();
    }
    
    public function deleteText(Task $task)
    {
        if($text = $this->find($task->getId()))
        {
            $this->getEntityManager()->remove($text);
            $this->getEntityManager()->flush();
        }
    }
    
}
